### ISSUE TITLE
Shannon Algorithm work incorrect

### ISSUE THREAD

**Issue by Artem-Verenko** [ncx-official/ICT-ShannonAlgorithm#8]
![image](https://user-images.githubusercontent.com/49845928/144592823-d963dc31-fbb9-40aa-ac71-bcc2a245f176.png)
![image](https://user-images.githubusercontent.com/49845928/144592886-856eca0b-02e7-43fd-8c85-929699c18022.png)

Алгоритм не працює, коли кодується рядок, що містить "1". Можливо ви не бачили цього)

**Comment by ncx-official** [comment]
Так існує проблема, коли на початку стоїть '1' або '0'. Наразі триває вирішення цієї проблеми.

**Comment by ncx-official** [comment]
Пофіксив баг, проблема заключалась в тому, що використовувалась функція Replace, яка кілька раз виконувалась. Тобто на прикладі "123" {1 -> "11", 2 -> "10", 3 -> "0"} строка конвертувалась в "120", далі в "1100", далі "11100" і в кінці ще раз конвертувала одиницю, яка щойно з'явилась. Тобто виходило "111100" що давало розкодований результат 1133. Дана проблема зустрічалась тільки із одиницями та нулями, наразі вона вирішена.
